### PR TITLE
Support password input types

### PR DESCRIPTION
**Pull request by akempes**

### CODE REVIEW

**Comment by kmlprtsng** [comment]
Hey, I need this change as well. Can you review this pull request please @protacon? Thanks.

**Comment by tarlepp** [comment]
Sorry @akempes and @kmlprtsng for late answer. First of all thanks for this PR - I'll take a closer look this weekend.

**Comment by suuuzi** [comment]
I need this change too :(

**Comment by tarlepp** [comment]
@akempes could you resolve those conflicts?

**Comment by bmendes2015** [comment]
Hey, I need this change, could please commit ?

**Comment by Hekku2** [comment]
This was fixed in #26

**Pull request closed without merging**
